[phases.setup]
nixPkgs = ["nodejs-22_x", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run --filter './apps/frontend' build"]

[start]
cmd = "bun run --filter './apps/frontend' start"

