[phases.setup]
nixPkgs = ["nodejs-22_x", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd apps/backend && bun run prisma:generate",
  "cd apps/backend && bun run build"
]

[start]
cmd = "cd apps/backend && bun run start:prod"
