[phases.setup]
nixPkgs = ["nodejs-22_x", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run --filter './apps/backend' prisma:generate", "bun run --filter './apps/backend' build"]

[start]
cmd = "bun run --filter './apps/backend' start:prod"
